import { Producto, Evento } from "./types";

export const MOCK_PRODUCTS: Producto[] = [
  {
    id: "1",
    nombre: "Blazer Vintage Camel",
    precio: 45,
    talla: "M",
    categoria: "mujer",
    estado: "Excelente",
    fotos_url: null,
    stock: 1,
    descripcion:
      "Blazer oversized en tono camel con estructura impecable. Forro interior en seda, botones dorados originales. Ideal para looks elevated thrift o business casual.",
    medidas: "Hombros 42cm · Largo 68cm · Busto 96cm",
    destacado: true,
    activo: true,
    stripe_price_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    nombre: "Vestido Midi Floral",
    precio: 38,
    talla: "S",
    categoria: "mujer",
    estado: "Como nuevo",
    fotos_url: null,
    stock: 1,
    descripcion:
      "Vestido midi con estampado floral en tonos terracota y crema. Escote en V, manga corta, caída perfecta. Una pieza única que no encontrarás en ninguna otra tienda.",
    medidas: "Busto 86cm · Cintura 70cm · Largo 105cm",
    destacado: true,
    activo: true,
    stripe_price_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    nombre: "Camisa Linen Oversized",
    precio: 28,
    talla: "L",
    categoria: "hombre",
    estado: "Bueno",
    fotos_url: null,
    stock: 1,
    descripcion:
      "Camisa de lino blanco roto, corte oversized. Perfecta para el clima boricua. Ligera, transpirable y con el carácter de una prenda con historia.",
    medidas: "Hombros 50cm · Pecho 116cm · Largo 80cm",
    destacado: true,
    activo: true,
    stripe_price_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    nombre: "Pantalón Wide Leg Camel",
    precio: 42,
    talla: "M",
    categoria: "mujer",
    estado: "Excelente",
    fotos_url: null,
    stock: 1,
    descripcion:
      "Pantalón wide leg en tono camel, tela estructurada de alta calidad. Cintura alta, bolsillos laterales. Una inversión de $42 que se paga sola.",
    medidas: "Cintura 72cm · Cadera 96cm · Largo 100cm",
    destacado: true,
    activo: true,
    stripe_price_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    nombre: "Cartera Estructurada Negra",
    precio: 35,
    talla: null,
    categoria: "accesorios",
    estado: "Excelente",
    fotos_url: null,
    stock: 1,
    descripcion:
      "Cartera structured en piel sintética de alta calidad, color negro. Cadena dorada desmontable, cierre magnético. Capacidad para teléfono, tarjetas y llaves.",
    medidas: "22cm × 15cm × 8cm",
    destacado: false,
    activo: true,
    stripe_price_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    nombre: "Jeans Mom Vintage",
    precio: 32,
    talla: "28",
    categoria: "mujer",
    estado: "Bueno",
    fotos_url: null,
    stock: 1,
    descripcion:
      "Jeans mom fit de los 90s con lavado vintage. Tiro alto, pierna recta. La prenda más icónica del thrift store elevado.",
    medidas: "Cintura 72cm · Cadera 96cm · Tiro 30cm · Largo 100cm",
    destacado: false,
    activo: true,
    stripe_price_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "7",
    nombre: "Chaqueta Denim Clásica",
    precio: 40,
    talla: "M",
    categoria: "hombre",
    estado: "Bueno",
    fotos_url: null,
    stock: 1,
    descripcion:
      "Chaqueta denim azul medio, corte clásico. Bolsillos al pecho, cierre de botones metálicos. Una pieza que mejora con el tiempo.",
    medidas: "Hombros 46cm · Pecho 104cm · Largo 62cm",
    destacado: false,
    activo: true,
    stripe_price_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "8",
    nombre: "Cinturón Piel Dorado",
    precio: 18,
    talla: null,
    categoria: "accesorios",
    estado: "Excelente",
    fotos_url: null,
    stock: 1,
    descripcion:
      "Cinturón fino de piel marrón con hebilla dorada. El accesorio que transforma cualquier outfit básico en algo curado.",
    medidas: "Largo total 95cm · Ancho 2.5cm",
    destacado: false,
    activo: true,
    stripe_price_id: null,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_EVENTOS: Evento[] = [
  {
    id: "1",
    titulo: "Pop Up — Condado",
    fecha: "2026-06-14",
    hora_inicio: "11:00 AM",
    hora_fin: "5:00 PM",
    ubicacion: "El Gancho, Condado, San Juan",
    descripcion:
      "Nuestro próximo pop up en Condado. Más de 50 piezas curadas, drops exclusivos y precios especiales para los primeros en llegar.",
    imagen_url: null,
    activo: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    titulo: "Mercado de Moda Sostenible",
    fecha: "2026-06-28",
    hora_inicio: "10:00 AM",
    hora_fin: "6:00 PM",
    ubicacion: "Plaza del Mercado, Santurce",
    descripcion:
      "Estaremos en el Mercado de Moda Sostenible de Santurce junto a otras marcas conscientes de Puerto Rico.",
    imagen_url: null,
    activo: true,
    created_at: new Date().toISOString(),
  },
];
